'use client';
import { useEffect,useState } from 'react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Empty } from '@/components/ui/empty';
import { Toaster } from '@/components/ui/sonner';
import { toast as notify } from 'sonner';
import { Thermometer,RefreshCw,MapPin,Clock,Database,FlaskConical,Check,AlertTriangle,WifiOff,ShieldX,Timer,Braces,Layers,Download,Sun,ArrowUpRight,Copy,LockKeyhole } from 'lucide-react';
import { resetEvaluationState,runFixture } from '@/lib/reading';
import { KMA_SOURCE } from '@/lib/kma';
import d1a from '@/public/t04-assets/fixtures/normal-d1-a.json';
import d1b from '@/public/t04-assets/fixtures/normal-d1-b.json';
import d2 from '@/public/t04-assets/fixtures/normal-d2.json';
import recover from '@/public/t04-assets/fixtures/recover-d2.json';
import timeout from '@/public/t04-assets/fixtures/timeout.json';
import auth from '@/public/t04-assets/fixtures/auth-401.json';
import rate from '@/public/t04-assets/fixtures/rate-429.json';
import offline from '@/public/t04-assets/fixtures/offline.json';
import schema from '@/public/t04-assets/fixtures/schema-break.json';
const failures=[{f:timeout,label:'응답 지연',icon:Timer},{f:auth,label:'원천 접근 거절',icon:ShieldX},{f:rate,label:'호출 제한',icon:Layers},{f:offline,label:'오프라인',icon:WifiOff},{f:schema,label:'형식 변경',icon:Braces}];
const messages:Record<string,{title:string,body:string,next:string}>={timeout:{title:'응답이 너무 늦어요',body:'제한시간 안에 원천의 응답을 받지 못했습니다.',next:'잠시 기다린 뒤 다시 시도해 주세요.'},auth:{title:'원천이 접근을 거절했어요',body:'외부 데이터 원천이 401/403으로 요청을 거절했습니다.',next:'원천 서비스의 공개 접근 상태를 확인하고 다시 시도해 주세요.'},rate_limit:{title:'요청이 잠시 제한됐어요',body:'외부 데이터 원천이 호출 제한(429)을 알렸습니다.',next:'60초 후 다시 시도해 주세요.'},offline:{title:'원천에 연결할 수 없어요',body:'네트워크 연결이 끊겨 데이터를 가져오지 못했습니다.',next:'인터넷 연결을 확인한 뒤 다시 시도해 주세요.'},schema_error:{title:'응답 형식이 달라졌어요',body:'필수 값이나 자료형이 예상한 형식과 일치하지 않습니다.',next:'원천의 응답 형식을 확인한 뒤 다시 시도해 주세요.'}};
function stamp(s:string|null){if(!s)return '원천에서 제공하지 않음';return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(s));}
function receipt(row:any){const r=row.reading;return {source_url:r.source_url,source_observed_at:r.source_time,normalized_value:r.normalized_value,unit:r.unit};}
export default function Page(){
 const [live,setLive]=useState<any>(resetEvaluationState());const [test,setTest]=useState<any>(resetEvaluationState());const [tab,setTab]=useState('live');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [selected,setSelected]=useState('');const [log,setLog]=useState<any[]>([]);const [source,setSource]=useState<any>(null);
 const state=tab==='live'?live:test;const reading=state.current_reading;const rows=state.daily_readings||[];const stale=state.status?.freshness==='stale';const msg=messages[state.status?.error_code];const comparison=state.last_comparison;const age=reading?(Date.now()-Date.parse(reading.fetched_at))/60000:0;
 async function request(body?:any){setBusy(true);setError('');try{const r=await fetch('/api/board',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j:any=await r.json();if(!r.ok)throw new Error(j.error);setLive(j);if(j.notice)flash(j.notice);return j;}catch(e){setError(e instanceof Error?e.message:'연결 실패. 기존 기록은 보존됩니다.');return null;}finally{setBusy(false);}}
 useEffect(()=>{void request();fetch('/source-info.json').then(r=>r.json()).then(setSource).catch(()=>{});},[]);
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const validate=(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('빈 객체를 전달해야 합니다.');};
  for(const action of ['read_board','refresh_board']){
   Promise.resolve(context.registerTool({name:action,title:action==='read_board'?'보존된 기온 기록 읽기':'실제 기온 조회하고 기록',description:action==='read_board'?'서버의 보존된 실제 일별 기록을 읽고 화면에 표시한다.':'고정 공개 원천의 실제 기온을 조회하고 KST 일별 기록을 저장한다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:action==='read_board',untrustedContentHint:true},execute:async(input:unknown)=>{validate(input);const result=await request(action==='refresh_board'?{action:'refresh'}:undefined);if(!result)throw new Error('원천 또는 저장소를 사용할 수 없습니다.');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {status:result.status,records:result.daily_readings.map((r:any)=>({date:r.record_date,...receipt(r)}))};}},{signal:lifecycle.signal})).catch(()=>{});
  }
  return ()=>lifecycle.abort();
 },[]);
 function flash(t:string){notify(t);}
 function replay(f:any,baseline=false){let start=baseline?runFixture(runFixture(resetEvaluationState(),d1a),d1b):test;const next=runFixture(start,f);setTest(next);setSelected(f.fixture_id);const match=next.status?.freshness===f.expected.freshness&&next.status?.error_code===f.expected.error_code&&next.daily_readings.length===f.expected.row_count&&next.current_reading?.normalized_value===f.expected.stored_value&&next.last_delta===f.expected.delta;setLog(l=>[...l,{id:f.fixture_id,pass:match,value:next.current_reading?.normalized_value,rows:next.daily_readings.length,status:next.status}]);}
 function reset(){setTest(resetEvaluationState());setSelected('');setLog([]);}
 async function copy(r:any){try{await navigator.clipboard.writeText(JSON.stringify(receipt(r),null,2));flash('영수증용 값 4개를 복사했습니다.');}catch{flash('아래 영수증용 값에서 직접 복사해 주세요.');}}
 function exportRecords(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({mode:tab,timezone:'Asia/Seoul',...state},null,2)],{type:'application/json'}));a.download=tab==='live'?'t04-real-records.json':'t04-synthetic-replay.json';a.click();URL.revokeObjectURL(a.href);}
 return <Tabs value={tab} onValueChange={setTab}><main>
  <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Thermometer size={22}/></span><span>가을의 온도<small>AUTUMN SIGNAL</small></span></a><div className="header-right"><span className="timezone"><Clock size={15}/> Asia/Seoul · KST</span><a className="source-link" href={source?.url||'#source'}><Braces size={17}/> 소스 보기</a></div></header>
  <div className="page-heading"><div><div className="eyebrow">DAILY INFORMATION BOARD <span>01 / WEATHER</span></div><h1>오늘의 공기를 기록하다<span>.</span></h1><p>대전 관측소의 최신 기온, 그리고 어제와의 작은 차이.</p></div><div className="location"><MapPin size={18}/><div>대한민국, 대전<small>기상청 관측지점 133</small></div></div></div>
  <div className="tabbar"><TabsList className="tabs" aria-label="데이터 모드"><TabsTrigger value="live" className={tab==='live'?'active':''}><Thermometer size={17}/>실제 정보판</TabsTrigger><TabsTrigger value="test" className={tab==='test'?'active':''}><FlaskConical size={17}/>실패 재생실</TabsTrigger></TabsList><span className="tab-caption">{tab==='live'?'공개 원천 · 실제 날짜 기록':'공개 fixture · 합성 데이터 전용'}</span></div>
  <TabsContent value={tab}>
  {tab==='test'&&<div className="synthetic-note"><FlaskConical size={18}/><span>합성 검사 모드입니다. 가상 날짜와 값은 실제 이틀의 기록을 대신하지 않습니다.</span><button className="text-button" onClick={reset}>합성 상태 초기화</button></div>}
  {error&&<div className="alert" role="alert"><AlertTriangle size={20}/>{error}<button onClick={()=>request()}>다시 불러오기</button></div>}
  <section className="dashboard">
   <div className={'temperature-card '+(stale?'is-stale':'')}>
    <div className="card-top"><span className="label">{tab==='live'?'대전 관측소 · 최신 관측 기온':'ALEPH · 합성 지수'}</span><span className={'status '+(stale?'warning':'')}><span/>{busy?'조회 중':stale?'오래된 값':reading?'정상 수신':'조회 대기'}</span></div>
    <div className="reading-row"><div className="value" key={String(reading?.normalized_value)}>{reading?reading.normalized_value.toFixed(tab==='live'?1:0):'—'}<span>{reading?.unit||(tab==='live'?'°C':'pt')}</span></div><div className="weather-symbol"><Sun size={70} strokeWidth={1}/></div></div>
    <div className="reading-caption">{tab==='live'?'기상청 관측소에서 측정한 기온 · 공개 기상실황표의 최신 관측값':'지정 공개 자산을 그대로 재생한 시험값입니다.'}</div>
    <div className="card-divider"/>
    <div className="time-grid"><div><span>출처 시각 · 관측 시각</span><strong>{stamp(reading?.source_time)}</strong></div><div><span>조회 시각</span><strong>{reading?stamp(reading.fetched_at):'아직 조회하지 않음'}</strong></div></div>
    <div className="source-row"><span>출처 <a href={reading?.source_url||(tab==='live'?KMA_SOURCE:'/t04-assets/README.md')} target="_blank" rel="noreferrer">{reading?.source_name||(tab==='live'?'기상청 날씨누리':'ALEPH 공개 합성 자산')}</a></span><span>KST · UTC+09:00</span></div>
    <div className="main-actions"><button className="primary" disabled={busy} onClick={()=>tab==='live'?request({action:'refresh'}):replay(stale?recover:d1a)}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'기온을 가져오는 중…':tab==='live'?'지금 조회하고 기록':stale?'다시 시도 · D2 복구':'정상 D1-A 재생'}</button><span>{tab==='live'?'같은 날은 한 줄로 갱신합니다.':'실제 기록에는 영향을 주지 않습니다.'}</span></div>
   </div>
   <aside className="side-stack"><div className="change-card"><div className="label">{rows.length>1&&rows[1].record_date!==new Date(new Date(rows[0].record_date+'T00:00:00+09:00').getTime()+86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'})?'이전 기록 대비':'어제 대비'}</div>{comparison?.state==='comparable'?<><div className="delta">{comparison.direction==='increase'?'+':comparison.direction==='decrease'?'−':''}{Number(comparison.magnitude.toFixed(1))}<span>{comparison.unit}</span></div><p>{comparison.direction==='increase'?'이전 기록보다 높아졌어요.':comparison.direction==='decrease'?'이전 기록보다 낮아졌어요.':'이전 기록과 같아요.'}</p><div className="formula">{rows.at(-1).normalized_value} − {rows.at(-2).normalized_value} = {Number((rows.at(-1).normalized_value-rows.at(-2).normalized_value).toFixed(1))} {comparison.unit}</div></>:<><div className="delta empty">아직 한 걸음</div><p>{rows.length?'다른 실제 KST 날짜에 다시 조회하면 두 기록을 비교할 수 있어요.':'첫 기록을 남기면 비교 준비가 시작돼요.'}</p><div className="mini-line"><span/><span/><span/><span/><span/></div></>}</div><div className="progress-card"><div className="progress-title"><Database size={19}/><span>{tab==='live'?'실제 날짜 기록':'합성 날짜 기록'}</span><strong>{rows.length}<small> / 2</small></strong></div><Progress className="progress-track" value={Math.min(rows.length/2,1)*100} aria-label="두 날짜 기록 진행률"/><p>{rows.length===0?'오늘의 첫 기록을 기다리고 있어요.':rows.length===1?'첫날 저장 완료. 다음 KST 날짜에 한 번 더.':'두 날짜 기록이 보존되어 있습니다.'}</p></div></aside>
  </section>
  {stale&&msg&&<section className="failure-banner" role="status"><AlertTriangle size={24}/><div><h3>{msg.title}</h3><p>{msg.body} 마지막 정상값 {reading?.normalized_value} {reading?.unit}을 보존했습니다.</p><strong>{msg.next}</strong><small>freshness: stale · error_code: {state.status.error_code}</small></div><button className="secondary" disabled={busy} onClick={()=>tab==='live'?request({action:'refresh'}):replay(recover)}><RefreshCw size={16}/>다시 시도{tab==='test'?' · D2 복구':''}</button></section>}
  {tab==='live'&&reading&&age>60&&!stale&&<div className="age-note"><Clock size={16}/> 마지막 성공 조회 이후 {Math.floor(age)}분이 지났습니다. 저장된 값이며 현재 기온과 다를 수 있습니다.</div>}
  {tab==='test'&&<section className="replay-panel"><div className="section-heading"><div><div className="eyebrow">FAILURE PLAYGROUND</div><h2>데이터가 오지 않는 순간</h2><p>실패 버튼은 정상 D1-A → D1-B 후 해당 실패를 재생합니다.</p></div><span className="package-pill">SHA-256 · 17/17 일치</span></div><div className="failure-options">{failures.map(({f,label,icon:Icon})=><button key={f.fixture_id} className={selected===f.fixture_id?'selected':''} onClick={()=>replay(f,true)}><Icon size={23}/><strong>{label}</strong><small>{f.fixture_id.replace('T04-','')}</small></button>)}</div><div className="sequence-controls"><span>정상 저장 순서</span><button onClick={()=>replay(d1a)}>D1-A · 100</button><button onClick={()=>replay(d1b)}>D1-B · 105</button><button onClick={()=>replay(d2)}>D2 · 120</button><button onClick={()=>replay(recover)}>복구 D2 · 120</button><span className="state-code">{state.status?`${state.status.freshness} / ${state.status.error_code}`:'빈 상태'}</span></div>{log.length>0&&<details className="run-log" open><summary>재생 결과 · {log.length}회</summary><div>{log.map((l,i)=><p key={i}><span className={l.pass?'pass':'fail'}>{l.pass?'일치':'순서 확인'}</span><code>{l.id}</code><span>{l.value} pt · {l.rows}행 · {l.status.freshness}/{l.status.error_code}</span></p>)}</div></details>}<details className="asset-details"><summary>공개 package ID와 파일 hash 대조</summary><p>aleph-t04-real-information-board-public-contract-v2</p><p>받은 17개 파일의 SHA-256을 manifest와 대조했습니다. 원본 파일을 아래에서 확인할 수 있습니다.</p><a href="/t04-assets/asset-manifest.json">SHA-256 목록</a> · <a href="/t04-assets/public-contract.json">판정 계약</a> · <a href="/t04-assets/README.md">공개 사용법</a></details></section>}
  <section className="records-section"><div className="section-heading"><div><div className="eyebrow">{tab==='live'?'REAL DAILY ARCHIVE':'SYNTHETIC DAILY ARCHIVE'}</div><h2>하루, 한 줄의 기록</h2></div><button className="secondary" disabled={!rows.length} onClick={exportRecords}><Download size={16}/>JSON 내보내기</button></div>{!rows.length?<Empty className="empty-record"><Database size={28}/><strong>아직 기록이 없어요.</strong><p>{tab==='live'?'지금 조회하고 기록 버튼으로 첫날을 남겨 주세요.':'정상 D1-A를 재생하거나 실패 버튼을 선택해 주세요.'}</p></Empty>:<div className="record-list">{rows.map((row:any,i:number)=><article className="record" key={row.record_id}><div className="record-head"><div><span className="day-number">DAY {String(i+1).padStart(2,'0')}</span><strong>{row.record_date}</strong><small>{row.locked?'확정된 실제 기록':tab==='live'?'실제 조회 · KST':'합성 날짜 · KST'}</small></div><div className="record-value">{row.normalized_value}<span> {row.unit}</span></div></div><details><summary>원자료 · 저장값 · 화면값 대조</summary><div className="match-grid"><div><span>원자료</span><strong>{row.raw?Number(row.raw.temperature_text):row.reading.normalized_value} {row.unit}</strong></div><div><span>일별 저장값</span><strong>{row.normalized_value} {row.unit}</strong></div><div><span>화면값</span><strong>{row.normalized_value} {row.unit}</strong></div></div><dl><dt>공개 원천 URL</dt><dd><a href={row.reading.source_url} target="_blank" rel="noreferrer">{row.reading.source_url}</a></dd><dt>원천 시각</dt><dd>{row.reading.source_time||'원천에서 제공하지 않음'}</dd><dt>조회 시각</dt><dd>{row.reading.fetched_at} / {stamp(row.reading.fetched_at)} KST</dd><dt>고유 기록 ID</dt><dd>{row.record_id}</dd></dl><details><summary>원자료 · 기상청 표 발췌</summary><pre>{JSON.stringify(row.raw||row.reading,null,2)}</pre></details>{tab==='live'&&<><h4>플랫폼 t04_day 영수증용 값</h4><pre>{JSON.stringify(receipt(row),null,2)}</pre><div className="receipt-actions"><button className="secondary" onClick={()=>copy(row)}><Copy size={15}/>값 4개 복사</button><button className="secondary" disabled={row.locked||busy} onClick={()=>request({action:'lock',date:row.record_date})}><LockKeyhole size={15}/>{row.locked?'기록 확정 완료':'이 날짜 기록 확정'}</button></div></>}</details></article>)}</div>}</section>
  </TabsContent>
  <footer><span>가을의 온도 <span className="footer-dot">/</span> 오늘의 진짜 정보판</span><span>공개 데이터만 기록합니다. <a href={KMA_SOURCE} target="_blank" rel="noreferrer">기상청 날씨누리 관측자료</a></span></footer>
  <Toaster position="bottom-center" theme="light"/>
 </main></Tabs>;
}
